[[session]]
name = "tmux config"
path = "~/code/dotfiles/dot-config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "vim config"
path = "~/code/dotfiles/dot-config/nvim"
startup_command = "nvim"

[[session]]
name = "balancehq"
path = "~/code/balancehq/balance"
startup_command = "balancehq"

[[session]]
name = "loanspark vault"
path = "~/Documents/Loanspark/"
startup_command = "loanspark-vault"
